import type { Metadata } from "next";
import { Inter } from "next/font/google"; // import Inter font
import "./globals.css";
import AppProvider from "@/provider/AppProvider";
import { Toaster } from "sonner";
import { Providers } from "@/components/sheard/session-provider";
import StripeProvider from "@/components/sheard/StripeProvider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Table Fresh",
  description: "Generated by create next app",
  icons: {
    icon: "/asset/logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased bg-[#F9F9F9]`}>
        <StripeProvider>
          <Providers>
            <AppProvider>
              {children}
              <Toaster />
            </AppProvider>
          </Providers>
        </StripeProvider>
      </body>
    </html>
  );
}
